apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.pathPrefix }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "request-dataset-deploy.fullname" . }}
            port:
              number: {{ .Values.service.port }}
